// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJssNr6OFw5W7DAJPT2u2iEugHmF1ao68',
    appId: '1:332187799493:web:ced3625a760a6e91fd05ac',
    messagingSenderId: '332187799493',
    projectId: 'chatapp-b6e6f',
    authDomain: 'chatapp-b6e6f.firebaseapp.com',
    storageBucket: 'chatapp-b6e6f.appspot.com',
    measurementId: 'G-DCJ4TJVHPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UJ7pzQvJLT7iUDKeIc6g1tXClf-7ffk',
    appId: '1:332187799493:android:f0e8238d1c63481bfd05ac',
    messagingSenderId: '332187799493',
    projectId: 'chatapp-b6e6f',
    storageBucket: 'chatapp-b6e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wotg7dKD2AnSrkFna9AsPuH0a9vboX4',
    appId: '1:332187799493:ios:a25534a16be234e5fd05ac',
    messagingSenderId: '332187799493',
    projectId: 'chatapp-b6e6f',
    storageBucket: 'chatapp-b6e6f.appspot.com',
    androidClientId: '332187799493-tm3lun48bbvcluq5cm4nqd87negdc2ds.apps.googleusercontent.com',
    iosClientId: '332187799493-a7vkqr4ttrei757e3559u4csfp3bml2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );
}