# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop
# name: "Build & Release"
# jobs:
#   build:
#     name: Build & Release
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       # - uses: actions/setup-java@v3
#       #   with:
#       #     distribution: "zulu"

#       #     java-version: "12"
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#           architecture: x64

#       #// apk
#       #  - run: flutter build apk --release --split-per-abi
#       # //web
#       - name: Build Flutter web
#         run: flutter build web --web-renderer html --release

#       #// ios
#       # - run: |
#       #     flutter build ios --no-codesign
#       #     cd build/ios/iphoneos
#       #     mkdir Payload
#       #     cd Payload
#       #     ln -s ../Runner.app
#       #     cd ..
#       #     zip -r app.ipa Payload
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           # artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
#           artifacts: "build/web/**"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.TOKEN }}

name: Flutter Web App CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Build web app
        run: flutter build web
      - name: Deploy to GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web
      - name: Deploy to GitHub Pages
        uses: actions/deploy-to-github-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_name: ${{ github.repository }}
          folder: build/web
